# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python JUNIPER-VIRTUALCHASSIS-MIB

FILENAME = "mib-jnx-virtualchassis.txt"

MIB = {
    "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",

    "JUNIPER-VIRTUALCHASSIS-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """Juniper Networks, Inc.""",
        "contact" : 
            """Juniper Technical Assistance Center
Juniper Networks, Inc.
1133 Innovation Way
  Sunnyvale, CA 94089
  E-mail: support@juniper.net""",
        "description" :
            """The MIB modules for Virtual Chassis Member.Virtual Chassis Member feature allows a set of
Juniper switches to be connected together to form a Virtual Chassis. A virtual chassis
will give all the features of a real chassis, potentially at a much lower cost points.
A virtual chassis will be managed as a single box and will appear as a single network
element to other switches and routers in the network. Some Juniper switches will have
the special high speed stacking ports which are used to connect to each other to form a 
stack. The Juniper switches can also be connected by the network ports to form a stack.
These can be used by Juniper switches that don't have dedicated stacking ports.""",
        "revisions" : (
            {
                "date" : "2014-03-18 00:00",
                "description" :
                    """Generalize the MIB description for other Juniper platforms and update 
the jnxVirtualChassisMemberId from 9 to 31.""",
            },
            {
                "date" : "2010-10-14 00:00",
                "description" :
                    """Modified the range for jnxVirtualChassisMemberPriority from 0 to 255.""",
            },
            {
                "date" : "2010-07-13 00:00",
                "description" :
                    """Added jnxVccpMemberUp and jnxVccpMemberDown Traps.""",
            },
        ),
        "identity node" : "jnxVirtualChassisMemberMIB",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "Counter64"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "NOTIFICATION-TYPE"},
        {"module" : "SNMPv2-TC", "name" : "MacAddress"},
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
        {"module" : "JUNIPER-MIB", "name" : "JnxChassisId"},
        {"module" : "JUNIPER-SMI", "name" : "jnxVccpNotifications"},
        {"module" : "JUNIPER-EX-SMI", "name" : "jnxExVirtualChassis"},
    ),

    "nodes" : {
        "jnxVirtualChassisMemberMIB" : {
            "nodetype" : "node",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1",
            "status" : "current",
        }, # node
        "jnxVirtualChassisMemberTable" : {
            "nodetype" : "table",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1",
            "status" : "current",
            "description" :
                """A list of virtual chassis Member information entries.""",
        }, # table
        "jnxVirtualChassisMemberEntry" : {
            "nodetype" : "row",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1",
            "status" : "current",
            "linkage" : [
                "jnxVirtualChassisMemberId",
            ],
            "description" :
                """An entry in the virtual chassis Member information table.""",
        }, # row
        "jnxVirtualChassisMemberId" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "31"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "31"
                    },
                },
            },
            "access" : "noaccess",
            "description" :
                """Identifies the virtual-chassis member.""",
        }, # column
        "jnxVirtualChassisMemberSerialnumber" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Serial number of the virtual-chassis member.""",
        }, # column
        "jnxVirtualChassisMemberRole" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "master" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "backup" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "linecard" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Specifies whether the virtual-chassis member is of the type:
master(1), backup(2), linecard (3) """,
        }, # column
        "jnxVirtualChassisMemberMacAddBase" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "MacAddress"},
            },
            "access" : "readonly",
            "description" :
                """Identifies Media Access Control Address base for the virtual-chassis member.""",
        }, # column
        "jnxVirtualChassisMemberSWVersion" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.5",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Identifies the JUNOS Base OS Software suite running on the virtual-chassis
member.""",
        }, # column
        "jnxVirtualChassisMemberPriority" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This specifies the priority of the virtual-chassis member which can
vary from 0 to 255.""",
        }, # column
        "jnxVirtualChassisMemberUptime" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.7",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """Specifies the virtual-chassis member uptime. """,
        }, # column
        "jnxVirtualChassisMemberModel" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "32"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "32"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Specifies the virtual-chassis member model. """,
        }, # column
        "jnxVirtualChassisMemberLocation" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.9",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Specifies the virtual-chassis member location. """,
        }, # column
        "jnxVirtualChassisMemberAlias" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.10",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Alias name for the virtual-chassis member.""",
        }, # column
        "jnxVirtualChassisMemberFabricMode" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.11",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Specifies virtual-chassis member's route mode. VC/VCF mode
indicates multi-path routing is disabled/enabled for the member. """,
        }, # column
        "jnxVirtualChassisMemberMixedMode" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.1.1.12",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Specifies virtual-chassis member's mixed mode. If mixed-mode is
is enabled, devices from different product families are allowed
to become virtual chassis member. """,
        }, # column
        "jnxVirtualChassisPortTable" : {
            "nodetype" : "table",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2",
            "status" : "current",
            "description" :
                """A list of virtual chassis port information entries.""",
        }, # table
        "jnxVirtualChassisPortEntry" : {
            "nodetype" : "row",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1",
            "status" : "current",
            "linkage" : [
                "jnxVirtualChassisFpcId",
                "jnxVirtualChassisPortName",
            ],
            "description" :
                """An entry in the virtual chassis port information table.""",
        }, # row
        "jnxVirtualChassisFpcId" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "31"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "31"
                    },
                },
            },
            "access" : "noaccess",
            "description" :
                """Identifies the virtual-chassis member.""",
        }, # column
        "jnxVirtualChassisPortName" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "127"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "127"
                    },
                },
            },
            "access" : "noaccess",
            "description" :
                """Indicates the port name of this
vccp port, which is typically but not limited to, a
function of the state of individual segments of
this port.""",
        }, # column
        "jnxVirtualChassisPortAdminStatus" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "up" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "down" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "unknown" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the actual admin status of this
vccp port, which is typically but not limited to, a
function of the state of individual segments of
this port.""",
        }, # column
        "jnxVirtualChassisPortOperStatus" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "up" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "down" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "unknown" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the actual operational status of this
vccp port, which is typically but not limited to, a
function of the state of individual segments of
this port.""",
        }, # column
        "jnxVirtualChassisPortInPkts" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.5",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of packets received on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortInPkts""",
        }, # column
        "jnxVirtualChassisPortOutPkts" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of packets sent from the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortOutPkts""",
        }, # column
        "jnxVirtualChassisPortInOctets" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.7",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of octets received on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortInOctets""",
        }, # column
        "jnxVirtualChassisPortOutOctets" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.8",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of octets sent on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortOutOctets""",
        }, # column
        "jnxVirtualChassisPortInMcasts" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.9",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of multicast packets received on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortInMcasts""",
        }, # column
        "jnxVirtualChassisPortOutMcasts" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.10",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of multicast packets sent from the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortOutMcasts""",
        }, # column
        "jnxVirtualChassisPortInPkts1secRate" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.11",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of packets received per second on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortInPkts1secRate""",
        }, # column
        "jnxVirtualChassisPortOutPkts1secRate" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.12",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of packets sent per second from the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortOutPkts1secRate""",
        }, # column
        "jnxVirtualChassisPortInOctets1secRate" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.13",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of octets received per secondon the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortInOctets1secRate""",
        }, # column
        "jnxVirtualChassisPortOutOctets1secRate" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.14",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of octets sent per second on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortOutOctets1secRate""",
        }, # column
        "jnxVirtualChassisPortCarrierTrans" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.15",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of Carrier errors on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortCarrierTrans""",
        }, # column
        "jnxVirtualChassisPortInCRCAlignErrors" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.16",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of Input CRC Alignment errors on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortInCRCAlignErrors""",
        }, # column
        "jnxVirtualChassisPortUndersizePkts" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.17",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of Undersize Packets on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortUndersizePkts""",
        }, # column
        "jnxVirtualChassisPortCollisions" : {
            "nodetype" : "column",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.3.40.1.4.1.2.1.18",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter64"},
            },
            "access" : "readonly",
            "description" :
                """Indicates the total number of Collisions on the 
virtual-chassis port. This object is a 64-bit version of 
jnxVirtualChassisPortCollisions""",
        }, # column
        "jnxVccpNotificationsPrefix" : {
            "nodetype" : "node",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.4.14.0",
            "status" : "current",
            "description" :
                """All Virtual Chassis notifications are registered
under this branch.""",
        }, # node
    }, # nodes

    "notifications" : {
        "jnxVccpPortUp" : {
            "nodetype" : "notification",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.4.14.0.1",
            "status" : "current",
            "objects" : {
                "jnxVirtualChassisPortAdminStatus" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisPortOperStatus" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberModel" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberLocation" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
            },
            "description" :
                """A PortUp trap signifies that the SNMP entity, acting in an
agent role, has detected that the jnxVirtualChassisPortOperStatus 
object for one of its communication links left the  down state
and transitioned into some other state (but not into the
notPresent state).  This other state is indicated by the
included value of jnxVirtualChassisPortOperStatus.""",
        }, # notification
        "jnxVccpPortDown" : {
            "nodetype" : "notification",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.4.14.0.2",
            "status" : "current",
            "objects" : {
                "jnxVirtualChassisPortAdminStatus" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisPortOperStatus" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberModel" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberLocation" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
            },
            "description" :
                """A PortDown trap signifies that the SNMP entity, acting in an
agent role, has detected that the jnxVirtualChassisPortOperStatus
object for one of its communication links is about to enter the
down state from some other state (but not into the
notPresent state).  This other state is indicated by the
included value of jnxVirtualChassisPortOperStatus.""",
        }, # notification
        "jnxVccpMemberUp" : {
            "nodetype" : "notification",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.4.14.0.3",
            "status" : "current",
            "objects" : {
                "jnxVirtualChassisMemberSerialnumber" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberRole" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberModel" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberLocation" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
            },
            "description" :
                """A MemberUp trap signifies that the SNMP entity, acting in an
agent role, has detected that the Member present at the location
jnxVirtualChassisMemberLocation on one of the Virtual
Chassis left the down state and transitioned into some other
state (but not into the notPresent state).""",
        }, # notification
        "jnxVccpMemberDown" : {
            "nodetype" : "notification",
            "moduleName" : "JUNIPER-VIRTUALCHASSIS-MIB",
            "oid" : "1.3.6.1.4.1.2636.4.14.0.4",
            "status" : "current",
            "objects" : {
                "jnxVirtualChassisMemberSerialnumber" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberRole" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberModel" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
                "jnxVirtualChassisMemberLocation" : {
                    "nodetype" : "object",
                    "module" : "JUNIPER-VIRTUALCHASSIS-MIB"
                },
            },
            "description" :
                """A MemberDown trap signifies that the SNMP entity, acting in an
agent role, has detected that the Member present at the location
jnxVirtualChassisMemberLocation on one of the Virtual
Chassis is about to enter the down state (but not into the notPresent
state).""",
        }, # notification
    }, # notifications

}
