version: 2

sphinx:
    configuration: doc/conf.py
    builder: html

python:
    version: 3.7
    install:
      - requirements: requirements.txt
      - method: pip
        path: .
        extra_requirements:
          - setuptools_scm
