name: Build NAV and run full test suite
on: [push, pull_request]

jobs:
  build-and-test:
    name: "Test on Python ${{ matrix.python-version}}"
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: "Cache pip packages"
        uses: pat-s/always-upload-cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "Cache tox environments"
        uses: pat-s/always-upload-cache@v2
        id: tox-cache
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt', '**/requirements/*.txt', 'tox.ini') }}

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Set environment variables"
        run: |
          echo "WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PGHOST=localhost" >> $GITHUB_ENV
          echo "PGUSER=nav" >> $GITHUB_ENV
          echo "PGPASSWORD=password" >> $GITHUB_ENV
          echo "=== Environment ==="
          env | sort
          echo "=== Working dir ==="
          pwd
          echo "=== Contents ==="
          ls -la


      - name: "Install test runner dependencies"
        run: |
          set -xe
          python -m pip install --upgrade pip setuptools wheel tox tox-gh-actions coverage virtualenv snmpsim
          sudo apt-get install -y nbtscan

      - name: "Install libraries needed to build external dependencies"
        run: |
          set -xe
          sudo apt-get install -y libldap2-dev libsasl2-dev libtidy5deb1 libsnmp35

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - uses: nanasess/setup-chromedriver@master

      - name: "Set up PostgreSQL"
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '9.4'  # minimum NAV requirement
          postgresql user: $PGUSER
          postgresql password: $PGPASSWORD

      - name: "Run tests"
        run: |
          export DISPLAY=:99
          ulimit -c unlimited
          sudo sysctl -w kernel.core_pattern=/tmp/core-%e.%p.%h.%t
          python -m tox

      - name: Upload test logs (${{ matrix.python-version }})
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-logs
          path: |
            /tmp/pytest-of-runner

      - name: Upload test reports (${{ matrix.python-version }})
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            reports/**/*

      - name: Upload core dumps (${{ matrix.python-version }})
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: core-dumps
          path: |
            /tmp/core-*

      - name: Try to print tracebacks of core dumps (${{ matrix.python-version }})
        if: failure()
        run: |
          sudo apt-get install -y gdb
          for core in /tmp/core-*; do
            echo "===== CORE: $core ====="
            execfn=$(file "$core" | sed -e 's/.*execfn: //' -e 's/, .*$//' | tr -d "'")
            gdb -ex bt "$execfn" "$core"
            echo
          done

  publish-test-results:
    name: "Publish test results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: "Publish test results"
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          check_name: "Test results"
          files: artifacts/**/*-results.xml
